<?php
require '../vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

// オプション設定
$options = new Options();
// デフォルトフォント
$options->set('defaultFont', 'sans-serif');
// HTML5タグを有効化
$options->set('isHtml5ParserEnabled', true);

// TODO:インスタンス化
$dompdf = new Dompdf($options);

// HTMLコンテンツ
$html = '
<style>
    h1 { color: #4f46e5; border-bottom: 2px solid #4f46e5; }
    p { font-size: 14px; line-height: 1.6; }
</style>
<h1>Dompdf Sample</h1>
<p>Hello! This is a PDF generated by dompdf.</p>
';

// TODO:読み込み: loadHtml()
$dompdf->loadHtml($html);

// TODO:用紙サイズ設定: setPaper()  A4, portrait
$dompdf->setPaper('A4', 'portrait');

// TODO:レンダリング: render()
$dompdf->render();

// TODO:出力（ブラウザで表示）: stream()
$dompdf->stream('dompdf_sample.pdf', ['Attachment' => false]);
